server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true #是否将自己注册到注册中心
    fetch-register: true #是否从eureka中获取信息
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
#设置feign客户端超时时间
ribbon:
  #指定是建立连接所用的时间，适用于网络状态正常的情况下，两端连接所用时间
  ReadTimeout: 5000
  #指定的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000
logging:
  level:
    com.atguigu.springcloud.service.PaymentFeignService: debug

